=== anakic/Packer/Packer/Schemas/table-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "Table schema",
  "description": "The schema for extracted table files.",
  "required": [
    "name",
    "lineageTag",
    "columns",
    "partitions"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "excludeFromModelRefresh": { "type": "boolean" },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "isPrivate": {
      "type": "boolean"
    },
    "isHidden": {
      "type": "boolean"
    },
    "showAsVariationsOnly": {
      "type": "boolean"
    },
    "lineageTag": {
      "type": "string"
    },
    "columns": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "required": [
          "name",
          "dataType"
        ],
        "properties": {
          "type": {
            "type": "string"
          },
          "sortByColumn": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dataType": {
            "type": "string"
          },
          "formatString": {
            "type": "string"
          },
          "isHidden": {
            "type": "boolean"
          },
          "isUnique": {
            "type": "boolean"
          },
          "isKey": {
            "type": "boolean"
          },
          "isNameInferred": {
            "type": "boolean"
          },
          "sourceColumn": {
            "type": "string"
          },
          "expression": {
            "type": "string"
          },
          "lineageTag": {
            "type": "string"
          },
          "columnOriginTable": {
            "type": "string"
          },
          "columnOriginColumn": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "errorMessage": {
            "type": "string"
          },
          "dataCategory": {
            "type": "string"
          },
          "summarizeBy": {
            "type": "string"
          },
          "isDataTypeInferred": {
            "type": "boolean"
          },
          "isNullable": {
            "type": "boolean"
          },
          "annotations": { "$ref": "#/defs/annotations" },
          "variations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": { "type": "string" },
                "isDefault": { "type": "boolean" },
                "defaultHierarchy": {
                  "type": "object",
                  "properties": {
                    "table": { "type": "string" },
                    "hierarcchy": { "type": "string" }
                  }
                },
                "relationship": {
                  "type": "string",
                  "format": "uuid"
                }
              }
            }
          },
          "attributeHierarchy": {
            "type": "object",
            "title": "The attributeHierarchy schema",
            "properties": {
              "state": {
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "extendedProperties": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": { "type": "string" },
                "name": { "type": "string" },
                "value": {
                  "type": "object",
                  "properties": {
                    "version": { "type": "number" },
                    "groupedColumns": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "Column": {
                            "type": "object",
                            "properties": {
                              "Expression": {
                                "type": "object",
                                "properties": {
                                  "SourceRef": {
                                    "type": "object",
                                    "properties": {
                                      "Entity": { "type": "string" }
                                    }
                                  }
                                }
                              },
                              "Property": { "type": "string" }
                            }
                          }
                        }
                      }
                    },
                    "binningMetadata": {
                      "type": "object",
                      "properties": {
                        "binSize": {
                          "type": "object",
                          "properties": {
                            "value": { "type": "number" },
                            "uint": { "type": "number" }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "additionalProperties": false
      }
    },
    "annotations": { "$ref": "#/defs/annotations" },
    "partitions": {
      "type": "array",
      "additionalItems": true,
      "items": {
        "type": "object",
        "required": [
          "name",
          "mode",
          "source"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "mode": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "source": {
            "type": "object",
            "required": [
              "type",
              "expression"
            ],
            "properties": {
              "type": {
                "type": "string"
              },
              "expression": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      }
    },
    "hierarchies": {
      "type": "array",
      "items": {
        "name": { "type": "string" },
        "lineageTag": {
          "type": "string",
          "format": "uuid"
        },
        "state": { "type": "string" },
        "levels": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "ordinal": { "type": "integer" },
              "column": { "type": "string" },
              "lineageTag": { "type": "string" }
            }
          }
        },
        "annotations": {
          "$ref": "#/defs/annotations"
        }
      }
    },
    "measures": {
      "type": "array",
      "items": {
        "name": { "type": "string" },
        "expression": { "type": "string" },
        "lineageTag": {
          "type": "string",
          "format": "uuid"
        },
        "annotations": { "$ref": "#/defs/annotations" }
      }
    }
  },
  "additionalProperties": false,
  "defs": {
    "annotations": {
      "$id": "/annotations",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "value": { "type": "string" }
        }
      }
    }
  }
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth Ward/table.json
{
  "name": "dbth Ward",
  "lineageTag": "40987abf-f635-427f-810d-e30a2fb64430",
  "columns": [
    {
      "name": "SYSSourceSystem",
      "dataType": "string",
      "sourceColumn": "SYSSourceSystem",
      "lineageTag": "5575fad1-cf36-44f1-8368-a64968852d2d",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "AgeGroupIntendedCode",
      "dataType": "int64",
      "sourceColumn": "AgeGroupIntendedCode",
      "lineageTag": "bf8dadb7-b256-4167-b4d7-7db766d3fe51",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"General\" />"
        }
      ]
    },
    {
      "name": "AvailableCountDays",
      "dataType": "double",
      "sourceColumn": "AvailableCountDays",
      "lineageTag": "71c367fc-2704-4d06-a81e-3dde72044008",
      "summarizeBy": "sum",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"General\" />"
        }
      ]
    },
    {
      "name": "AvailableCountNights",
      "dataType": "double",
      "sourceColumn": "AvailableCountNights",
      "lineageTag": "24e17990-aa3f-4891-947f-4a263be766bd",
      "summarizeBy": "sum",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"General\" />"
        }
      ]
    },
    {
      "name": "BedCountNurse",
      "dataType": "double",
      "sourceColumn": "BedCountNurse",
      "lineageTag": "0a357a3f-2439-4c33-924b-1986ec552859",
      "summarizeBy": "sum",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"General\" />"
        }
      ]
    },
    {
      "name": "BedCountConsultant",
      "dataType": "double",
      "sourceColumn": "BedCountConsultant",
      "lineageTag": "5fd7907c-e5fc-416a-92ec-50bcc1a39f3d",
      "summarizeBy": "sum",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"General\" />"
        }
      ]
    },
    {
      "name": "DateFrom",
      "dataType": "dateTime",
      "sourceColumn": "DateFrom",
      "formatString": "General Date",
      "lineageTag": "8760674a-5fdd-418c-9235-e8c7eff24acd",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
        }
      ]
    },
    {
      "name": "DateTo",
      "dataType": "string",
      "sourceColumn": "DateTo",
      "lineageTag": "2ea575ad-003c-4476-b591-fa7499027a0b",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "DayNightAvailabilityDescription",
      "dataType": "string",
      "sourceColumn": "DayNightAvailabilityDescription",
      "lineageTag": "93612d13-59bc-468f-8a6a-810ca7d3e1ad",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "SexGroupDescription",
      "dataType": "string",
      "sourceColumn": "SexGroupDescription",
      "lineageTag": "dffbf3ad-230e-4a86-94f3-a1b83eca1c6d",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "SexOfPatientsCode",
      "dataType": "double",
      "sourceColumn": "SexOfPatientsCode",
      "lineageTag": "8ac2778e-fb96-4aaa-8ede-62fc19508e56",
      "summarizeBy": "count",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"General\" />"
        }
      ]
    },
    {
      "name": "SMTWTFSAvailabilityMatrixDay",
      "dataType": "string",
      "sourceColumn": "SMTWTFSAvailabilityMatrixDay",
      "lineageTag": "06933504-6832-413e-b31e-4125adbffcc8",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "SMTWTFSAvailabilityMatrixNight",
      "dataType": "string",
      "sourceColumn": "SMTWTFSAvailabilityMatrixNight",
      "lineageTag": "2bfb0e88-e0bd-4313-9132-62d200287864",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "WardCode",
      "dataType": "string",
      "sourceColumn": "WardCode",
      "lineageTag": "bdd13c5d-f8ea-4b7c-bbd9-404fd1bf6c1c",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "WardName",
      "dataType": "string",
      "sourceColumn": "WardName",
      "lineageTag": "668f8e53-5eaf-4a99-ba25-fdfcdf899aec",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "HospitalCode",
      "dataType": "string",
      "sourceColumn": "HospitalCode",
      "lineageTag": "818b8022-75f9-4d70-ad8c-6b7c7e3ebee8",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "IntendedClinicalCareIntensityCode",
      "dataType": "int64",
      "sourceColumn": "IntendedClinicalCareIntensityCode",
      "formatString": "0",
      "lineageTag": "0a5c112b-5a73-4660-b0e4-166cfb50f5ac",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        }
      ]
    },
    {
      "name": "Type",
      "dataType": "string",
      "sourceColumn": "Type",
      "lineageTag": "7eec76f2-0b2b-4a1c-a9f4-563317e831b1",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "Kind",
      "dataType": "string",
      "sourceColumn": "Kind",
      "lineageTag": "42eb5f5a-a640-4a4d-96a0-0ce7638d98c3",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "type": "calculated",
      "name": "TypeKind",
      "dataType": "string",
      "isDataTypeInferred": true,
      "expression": "{ref: ColumnExpressions\\TypeKind.dax}",
      "lineageTag": "ad0fd5a6-eb68-480a-b5b3-566e652ebc53",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth Ward-bc249986-19fd-42ec-a9c3-c1a4944735c3",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth Ward-bc249986-19fd-42ec-a9c3-c1a4944735c3.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth WardIntendedClinicalCareIntensity/table.json
{
  "name": "dbth WardIntendedClinicalCareIntensity",
  "lineageTag": "594e8350-a8b3-41cf-861a-aeeb7a1c33aa",
  "columns": [
    {
      "name": "Code",
      "dataType": "int64",
      "sourceColumn": "Code",
      "formatString": "0",
      "lineageTag": "342dba40-4b97-4ccb-96be-ef48ba7332aa",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "62361de2-181f-4fb8-a357-42e9e44971e9",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth WardIntendedClinicalCareIntensity-bc1f50b7-20ad-4bfc-9702-9d8f3eee4965",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth WardIntendedClinicalCareIntensity-bc1f50b7-20ad-4bfc-9702-9d8f3eee4965.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth Episode/table.json
{
  "name": "dbth Episode",
  "lineageTag": "f43c0c29-edee-4a65-a08c-2af66516b3d0",
  "columns": [
    {
      "name": "Id",
      "dataType": "int64",
      "sourceColumn": "Id",
      "formatString": "0",
      "lineageTag": "aa9ff904-f466-4dd4-a4cc-6c332749f412",
      "summarizeBy": "count",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "Int64#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Id"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "SpellId",
      "dataType": "int64",
      "sourceColumn": "SpellId",
      "formatString": "0",
      "lineageTag": "2d3ca61a-ef9d-4c44-a37e-5c70b8e6d669",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "Int64#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "SpellId"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "SourceSystem",
      "dataType": "string",
      "sourceColumn": "SourceSystem",
      "lineageTag": "fc8eb5b7-2714-4a13-832f-ae1050acb0aa",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "String#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "SourceSystem"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "ConsultantMainSpecialty",
      "dataType": "int64",
      "sourceColumn": "ConsultantMainSpecialty",
      "formatString": "0",
      "lineageTag": "64b2cb33-2726-493e-9a0a-8c3d16958e2b",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "Int64#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "ConsultantMainSpecialty"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "Start",
      "dataType": "dateTime",
      "sourceColumn": "Start",
      "formatString": "General Date",
      "lineageTag": "9570a4e1-78fa-4460-9ee9-298e8da24f99",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "DateTime#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Start"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "End",
      "dataType": "dateTime",
      "sourceColumn": "End",
      "formatString": "General Date",
      "lineageTag": "0c548bf5-3eb4-4e36-8d09-c975e2d4db85",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "DateTime#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "End"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "Number",
      "dataType": "int64",
      "sourceColumn": "Number",
      "formatString": "0",
      "lineageTag": "26fece22-5cf7-486c-b736-3d57cf5b66a8",
      "summarizeBy": "sum",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "Int64#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Number"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "CodingStatus",
      "dataType": "string",
      "sourceColumn": "CodingStatus",
      "lineageTag": "053f4691-a1d3-4619-aaab-e0ff0605c902",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "type": "calculated",
      "name": "DateStart",
      "dataType": "dateTime",
      "isDataTypeInferred": true,
      "expression": "{ref: ColumnExpressions\\DateStart.dax}",
      "formatString": "General Date",
      "lineageTag": "925b7d06-a1e4-428e-be75-dffb93efe140",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
        }
      ]
    },
    {
      "type": "calculated",
      "name": "DateEnd",
      "dataType": "dateTime",
      "isDataTypeInferred": true,
      "expression": "{ref: ColumnExpressions\\DateEnd.dax}",
      "formatString": "General Date",
      "lineageTag": "1ad13aad-1755-4c7a-a519-c70fcce4284a",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth Episode-aac5c86b-2ba1-4fa7-9f6c-b4fef6c74871",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth Episode-aac5c86b-2ba1-4fa7-9f6c-b4fef6c74871.m}"
      }
    }
  ],
  "measures": [
    {
      "name": "Episodes in perdiod",
      "expression": "{ref: MeasureExpressions\\Episodes in perdiod.dax}",
      "lineageTag": "75616879-f70b-40f5-ae17-755a8039daa8"
    },
    {
      "name": "Episode Days in period",
      "expression": "{ref: MeasureExpressions\\Episode Days in period.dax}",
      "formatString": "0",
      "lineageTag": "593cf6a4-ec93-4faf-b16a-6469277dd853",
      "annotations": [
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        }
      ]
    }
  ],
  "annotations": [
    {
      "name": "PBI_DescriptionAtRefresh"
    },
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth WardIntendedAgeGroup/table.json
{
  "name": "dbth WardIntendedAgeGroup",
  "lineageTag": "9a3ccad7-1425-43d9-b696-1bd69559c70d",
  "columns": [
    {
      "name": "Code",
      "dataType": "int64",
      "sourceColumn": "Code",
      "formatString": "0",
      "lineageTag": "aac2f00b-4848-4e6e-b39a-124ec24c5e14",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "7d60c36f-81ca-48a5-a45d-064881dad082",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth WardIntendedAgeGroup-a968774b-8c82-4bcc-9073-1e32c98176e3",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth WardIntendedAgeGroup-a968774b-8c82-4bcc-9073-1e32c98176e3.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}
