=== anakic/Packer/Packer/Schemas/table-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "Table schema",
  "description": "The schema for extracted table files.",
  "required": [
    "name",
    "lineageTag",
    "columns",
    "partitions"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "excludeFromModelRefresh": { "type": "boolean" },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "isPrivate": {
      "type": "boolean"
    },
    "isHidden": {
      "type": "boolean"
    },
    "showAsVariationsOnly": {
      "type": "boolean"
    },
    "lineageTag": {
      "type": "string"
    },
    "columns": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "required": [
          "name",
          "dataType"
        ],
        "properties": {
          "type": {
            "type": "string"
          },
          "sortByColumn": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dataType": {
            "type": "string"
          },
          "formatString": {
            "type": "string"
          },
          "isHidden": {
            "type": "boolean"
          },
          "isUnique": {
            "type": "boolean"
          },
          "isKey": {
            "type": "boolean"
          },
          "isNameInferred": {
            "type": "boolean"
          },
          "sourceColumn": {
            "type": "string"
          },
          "expression": {
            "type": "string"
          },
          "lineageTag": {
            "type": "string"
          },
          "columnOriginTable": {
            "type": "string"
          },
          "columnOriginColumn": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "errorMessage": {
            "type": "string"
          },
          "dataCategory": {
            "type": "string"
          },
          "summarizeBy": {
            "type": "string"
          },
          "isDataTypeInferred": {
            "type": "boolean"
          },
          "isNullable": {
            "type": "boolean"
          },
          "annotations": { "$ref": "#/defs/annotations" },
          "variations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": { "type": "string" },
                "isDefault": { "type": "boolean" },
                "defaultHierarchy": {
                  "type": "object",
                  "properties": {
                    "table": { "type": "string" },
                    "hierarcchy": { "type": "string" }
                  }
                },
                "relationship": {
                  "type": "string",
                  "format": "uuid"
                }
              }
            }
          },
          "attributeHierarchy": {
            "type": "object",
            "title": "The attributeHierarchy schema",
            "properties": {
              "state": {
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "extendedProperties": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": { "type": "string" },
                "name": { "type": "string" },
                "value": {
                  "type": "object",
                  "properties": {
                    "version": { "type": "number" },
                    "groupedColumns": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "Column": {
                            "type": "object",
                            "properties": {
                              "Expression": {
                                "type": "object",
                                "properties": {
                                  "SourceRef": {
                                    "type": "object",
                                    "properties": {
                                      "Entity": { "type": "string" }
                                    }
                                  }
                                }
                              },
                              "Property": { "type": "string" }
                            }
                          }
                        }
                      }
                    },
                    "binningMetadata": {
                      "type": "object",
                      "properties": {
                        "binSize": {
                          "type": "object",
                          "properties": {
                            "value": { "type": "number" },
                            "uint": { "type": "number" }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "additionalProperties": false
      }
    },
    "annotations": { "$ref": "#/defs/annotations" },
    "partitions": {
      "type": "array",
      "additionalItems": true,
      "items": {
        "type": "object",
        "required": [
          "name",
          "mode",
          "source"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "mode": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "source": {
            "type": "object",
            "required": [
              "type",
              "expression"
            ],
            "properties": {
              "type": {
                "type": "string"
              },
              "expression": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      }
    },
    "hierarchies": {
      "type": "array",
      "items": {
        "name": { "type": "string" },
        "lineageTag": {
          "type": "string",
          "format": "uuid"
        },
        "state": { "type": "string" },
        "levels": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "ordinal": { "type": "integer" },
              "column": { "type": "string" },
              "lineageTag": { "type": "string" }
            }
          }
        },
        "annotations": {
          "$ref": "#/defs/annotations"
        }
      }
    },
    "measures": {
      "type": "array",
      "items": {
        "name": { "type": "string" },
        "expression": { "type": "string" },
        "lineageTag": {
          "type": "string",
          "format": "uuid"
        },
        "annotations": { "$ref": "#/defs/annotations" }
      }
    }
  },
  "additionalProperties": false,
  "defs": {
    "annotations": {
      "$id": "/annotations",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "value": { "type": "string" }
        }
      }
    }
  }
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth AttendanceDisposal/table.json
{
  "name": "dbth AttendanceDisposal",
  "lineageTag": "5384e30e-25dd-4ecb-b03e-7dc1d3d980bc",
  "columns": [
    {
      "name": "Code",
      "dataType": "int64",
      "sourceColumn": "Code",
      "formatString": "0",
      "lineageTag": "bee20967-0cb1-427d-9819-12509fdfc0bb",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "43fa9d18-c6c1-4483-8b43-72b77baae1c4",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "Category",
      "dataType": "string",
      "sourceColumn": "Category",
      "lineageTag": "3fe86ed7-2b53-4f11-824e-446ff0280615",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth AttendanceDisposal-193a7b72-b2cf-43e6-b05a-db522c7d7162",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth AttendanceDisposal-193a7b72-b2cf-43e6-b05a-db522c7d7162.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth AdministrativeCategory/table.json
{
  "name": "dbth AdministrativeCategory",
  "lineageTag": "429df64e-b1ec-4fa8-b661-c176f99707e4",
  "columns": [
    {
      "name": "Code",
      "dataType": "int64",
      "sourceColumn": "Code",
      "formatString": "0",
      "lineageTag": "286e62c5-83d2-4c8a-8439-46694e2a6242",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "Int64#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Code"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "6e454be6-10e2-409b-8a3b-83c414a8f847",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "String#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Description"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth AdministrativeCategory-8a5182be-646a-498d-8c73-c54d480fbd54",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth AdministrativeCategory-8a5182be-646a-498d-8c73-c54d480fbd54.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_DescriptionAtRefresh"
    },
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth AdmissionMethod/table.json
{
  "name": "dbth AdmissionMethod",
  "lineageTag": "a0393f85-ae1c-4c52-b112-fb3161a26872",
  "columns": [
    {
      "name": "Code",
      "dataType": "string",
      "sourceColumn": "Code",
      "lineageTag": "1db13c25-9d07-4c31-bc55-9ec8b8e55553",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "String#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Code"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "ecfff809-fb54-4d29-b04a-9128f66a2f14",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "String#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Description"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth AdmissionMethod-0ed87f57-2c09-4fa0-8438-f3aca16f4fbd",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth AdmissionMethod-0ed87f57-2c09-4fa0-8438-f3aca16f4fbd.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_DescriptionAtRefresh"
    },
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth DischargeMethod/table.json
{
  "name": "dbth DischargeMethod",
  "lineageTag": "7a2c2e41-2d5e-46c5-9a15-5cc4d0ec15e9",
  "columns": [
    {
      "name": "Code",
      "dataType": "int64",
      "sourceColumn": "Code",
      "formatString": "0",
      "lineageTag": "94d2fc18-11f7-4418-b085-1c59f5c3dda1",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "Int64#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Code"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "be51c42e-dd5f-4257-bc0f-a305b7d0805b",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "String#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Description"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth DischargeMethod-59a6cb4a-057a-4682-8f64-0b4f8d739391",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth DischargeMethod-59a6cb4a-057a-4682-8f64-0b4f8d739391.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_DescriptionAtRefresh"
    },
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth HospitalSite/table.json
{
  "name": "dbth HospitalSite",
  "lineageTag": "d0c80c41-cd3b-4cdc-ba63-7dcd794b5d15",
  "columns": [
    {
      "name": "Code",
      "dataType": "string",
      "sourceColumn": "Code",
      "lineageTag": "8978e92c-9769-4aea-a875-b65ea112f03e",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    },
    {
      "name": "Name",
      "dataType": "string",
      "sourceColumn": "Name",
      "lineageTag": "27fea52a-282d-4adb-a6a5-4caf5c8cc022",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth HospitalSite-625fbd8a-3664-42cc-bd5a-4e299a0f5e39",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth HospitalSite-625fbd8a-3664-42cc-bd5a-4e299a0f5e39.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth DischargeDestination/table.json
{
  "name": "dbth DischargeDestination",
  "lineageTag": "a1ea1e0e-5cbf-4994-9947-0afec2b17204",
  "columns": [
    {
      "name": "Code",
      "dataType": "int64",
      "sourceColumn": "Code",
      "formatString": "0",
      "lineageTag": "b73412c8-2a22-4f3d-9c3e-d4dace1b93bf",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "Int64#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Code"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "dcac8fe0-9d37-470a-8fe7-7bfb89b86ba1",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "String#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Description"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth DischargeDestination-5bb31d1e-0980-4b75-a478-37376f72745d",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth DischargeDestination-5bb31d1e-0980-4b75-a478-37376f72745d.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_DescriptionAtRefresh"
    },
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth AttendanceCategory/table.json
{
  "name": "dbth AttendanceCategory",
  "lineageTag": "a68ab7c4-f9d7-475d-a571-11a55a05b27a",
  "columns": [
    {
      "name": "Code",
      "dataType": "int64",
      "sourceColumn": "Code",
      "formatString": "0",
      "lineageTag": "dcebd23b-9d1d-4d27-8489-ee00128d70ac",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "Int64#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Code"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "72850f8c-58e2-4f2c-a22b-939337e640f7",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "String#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Description"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth AttendanceCategory-8fbbb449-7be2-4e7c-94ba-1d4409acbeb0",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth AttendanceCategory-8fbbb449-7be2-4e7c-94ba-1d4409acbeb0.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_DescriptionAtRefresh"
    },
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth MainSpecialty/table.json
{
  "name": "dbth MainSpecialty",
  "lineageTag": "a04f6dee-9c0d-41b3-b739-080dd92d08af",
  "columns": [
    {
      "name": "Code",
      "dataType": "int64",
      "sourceColumn": "Code",
      "formatString": "0",
      "lineageTag": "9e2879f3-19b0-4df6-a293-54da606bd1e0",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "2d60f32a-c1fb-4587-9866-27dd7eb9b04e",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth MainSpecialty-0fb6274c-2f8e-4e8b-92d3-4057bf94b7d6",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth MainSpecialty-0fb6274c-2f8e-4e8b-92d3-4057bf94b7d6.m}"
      }
    }
  ],
  "annotations": [
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}
