=== anakic/Packer/Packer/Schemas/table-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "Table schema",
  "description": "The schema for extracted table files.",
  "required": [
    "name",
    "lineageTag",
    "columns",
    "partitions"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "excludeFromModelRefresh": { "type": "boolean" },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "isPrivate": {
      "type": "boolean"
    },
    "isHidden": {
      "type": "boolean"
    },
    "showAsVariationsOnly": {
      "type": "boolean"
    },
    "lineageTag": {
      "type": "string"
    },
    "columns": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "required": [
          "name",
          "dataType"
        ],
        "properties": {
          "type": {
            "type": "string"
          },
          "sortByColumn": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dataType": {
            "type": "string"
          },
          "formatString": {
            "type": "string"
          },
          "isHidden": {
            "type": "boolean"
          },
          "isUnique": {
            "type": "boolean"
          },
          "isKey": {
            "type": "boolean"
          },
          "isNameInferred": {
            "type": "boolean"
          },
          "sourceColumn": {
            "type": "string"
          },
          "expression": {
            "type": "string"
          },
          "lineageTag": {
            "type": "string"
          },
          "columnOriginTable": {
            "type": "string"
          },
          "columnOriginColumn": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "errorMessage": {
            "type": "string"
          },
          "dataCategory": {
            "type": "string"
          },
          "summarizeBy": {
            "type": "string"
          },
          "isDataTypeInferred": {
            "type": "boolean"
          },
          "isNullable": {
            "type": "boolean"
          },
          "annotations": { "$ref": "#/defs/annotations" },
          "variations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": { "type": "string" },
                "isDefault": { "type": "boolean" },
                "defaultHierarchy": {
                  "type": "object",
                  "properties": {
                    "table": { "type": "string" },
                    "hierarcchy": { "type": "string" }
                  }
                },
                "relationship": {
                  "type": "string",
                  "format": "uuid"
                }
              }
            }
          },
          "attributeHierarchy": {
            "type": "object",
            "title": "The attributeHierarchy schema",
            "properties": {
              "state": {
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "extendedProperties": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": { "type": "string" },
                "name": { "type": "string" },
                "value": {
                  "type": "object",
                  "properties": {
                    "version": { "type": "number" },
                    "groupedColumns": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "Column": {
                            "type": "object",
                            "properties": {
                              "Expression": {
                                "type": "object",
                                "properties": {
                                  "SourceRef": {
                                    "type": "object",
                                    "properties": {
                                      "Entity": { "type": "string" }
                                    }
                                  }
                                }
                              },
                              "Property": { "type": "string" }
                            }
                          }
                        }
                      }
                    },
                    "binningMetadata": {
                      "type": "object",
                      "properties": {
                        "binSize": {
                          "type": "object",
                          "properties": {
                            "value": { "type": "number" },
                            "uint": { "type": "number" }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "additionalProperties": false
      }
    },
    "annotations": { "$ref": "#/defs/annotations" },
    "partitions": {
      "type": "array",
      "additionalItems": true,
      "items": {
        "type": "object",
        "required": [
          "name",
          "mode",
          "source"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "mode": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "source": {
            "type": "object",
            "required": [
              "type",
              "expression"
            ],
            "properties": {
              "type": {
                "type": "string"
              },
              "expression": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      }
    },
    "hierarchies": {
      "type": "array",
      "items": {
        "name": { "type": "string" },
        "lineageTag": {
          "type": "string",
          "format": "uuid"
        },
        "state": { "type": "string" },
        "levels": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "ordinal": { "type": "integer" },
              "column": { "type": "string" },
              "lineageTag": { "type": "string" }
            }
          }
        },
        "annotations": {
          "$ref": "#/defs/annotations"
        }
      }
    },
    "measures": {
      "type": "array",
      "items": {
        "name": { "type": "string" },
        "expression": { "type": "string" },
        "lineageTag": {
          "type": "string",
          "format": "uuid"
        },
        "annotations": { "$ref": "#/defs/annotations" }
      }
    }
  },
  "additionalProperties": false,
  "defs": {
    "annotations": {
      "$id": "/annotations",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "value": { "type": "string" }
        }
      }
    }
  }
}

=== anakic/Packer/Packer.Tests2/TestFiles/UnpackedDb/Tables/dbth SourceOfAdmission/table.json
{
  "name": "dbth SourceOfAdmission",
  "lineageTag": "512d45b7-8c9d-41d2-b4eb-d5d722c1c953",
  "columns": [
    {
      "name": "Code",
      "dataType": "int64",
      "sourceColumn": "Code",
      "formatString": "0",
      "lineageTag": "b1b2bc44-5850-4361-90f2-9f29daa2b523",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "Int64#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Code"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    },
    {
      "name": "Description",
      "dataType": "string",
      "sourceColumn": "Description",
      "lineageTag": "abcbf7a5-277c-4764-be7d-3e8329c1ad7c",
      "summarizeBy": "none",
      "annotations": [
        {
          "name": "SummarizationSetBy",
          "value": "Automatic"
        },
        {
          "name": "Format",
          "value": "<Format Format=\"Text\" />"
        },
        {
          "name": "DataTypeAtRefresh",
          "value": "String#####not a type"
        },
        {
          "name": "PBI_NameAtRefresh",
          "value": "Description"
        },
        {
          "name": "PBI_WasHiddenAtRefresh",
          "value": "False"
        }
      ]
    }
  ],
  "partitions": [
    {
      "name": "dbth SourceOfAdmission-62c0924b-e876-44f7-96b8-a37023ba8b6d",
      "mode": "import",
      "source": {
        "type": "m",
        "expression": "{ref: PartitionExpressions\\dbth SourceOfAdmission-62c0924b-e876-44f7-96b8-a37023ba8b6d.m}"
      }
    }
  ],
  "measures": [
    {
      "name": "Measure",
      "expression": "{ref: MeasureExpressions\\Measure.dax}",
      "formatString": "0",
      "lineageTag": "ff7df3a1-7fdd-44f2-be61-1ef013433358",
      "annotations": [
        {
          "name": "Format",
          "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
        }
      ]
    }
  ],
  "annotations": [
    {
      "name": "PBI_DescriptionAtRefresh"
    },
    {
      "name": "PBI_ResultType",
      "value": "Table"
    }
  ]
}
